version: 0.2

env:
  variables:
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - aws --version
      - $(aws ecr get-login --no-include-email --region eu-north-1)
  build:
    commands:
      - docker build -t repo/image:$IMAGE_TAG .
      - docker push repo/image:$IMAGE_TAG
  post_build:
    commands:
      - kubectl apply -f deployment.yaml